feat(Dropdown): ✨ New component
digdir/designsystem pull request #1070
Opened 2023-11-08 09:37 UTC by Barsnes

Resolves #1067

2023-11-13 10:29 UTC, Thuneer requested changes
I have updated the component in Figma with some new changes:
* Added a large variant
* Changed heading text color to subtle.
* Apply the same responsive mobile logic as on the modal (100% width)

2023-11-13 11:10 UTC, mimarz requested changes
- This is a confusing component to review in terms of features 🙈 

- I kinda feel this component should be called `Menu` or `DropdownMenu`. What do you guys think? I know its called `Dropdown` to stay in sync with Aksel, but I feel its confusing, I keep thinking its a `Select` 😅 

- Is it still correct to use the roles `menu` and `menuitem` now that its tabbable? I see its done very differently in other designsystems. Danske's [Overflow menu](https://designsystem.dk/komponenter/overflowmenu/) does not have them, and their component looks the most similar to what we are trying to achieve. Lets not forget that no aria is better than "bad" aria.

2023-11-13 11:20 UTC, Barsnes commented on packages/react/src/components/Dropdown/DropdownGroup/DropdownGroup.tsx
> +            as='h2'
I believe since it is a menu context, it should use `h2`. @Thuneer probably has a good answer to this

2023-11-13 11:23 UTC, Barsnes commented on packages/react/src/components/Dropdown/DropdownDivider/DropdownDivider.tsx
> +export const DropdownDivider = ({ ...rest }: DropdownDividerProps) => {
> Can't we just use the `Divider` directly in the component? If we need some changes for it to fit here, maybe see if we can adapt `Divider`
> 
> We should prefer composability of our components as `Card`, `Modal` and `Popover` will also probably need dividers and making a wrapper component for all of those also can induce a lot of unnecessary overhead.

We should, but the color should always be `subtle`, according to the design, which can't be done if we don't have a wrapper component

2023-11-15 08:32 UTC, Barsnes commented
> * I kinda feel this component should be called `Menu` or `DropdownMenu`. What do you guys think? I know its called `Dropdown` to stay in sync with Aksel, but I feel its confusing, I keep thinking its a `Select` 😅
`DropdownMenu` would work fine, since it is an actual menu 👍🏼

> * Is it still correct to use the roles `menu` and `menuitem` now that its tabbable? I see its done very differently in other designsystems. Danske's [Overflow menu](https://designsystem.dk/komponenter/overflowmenu/) does not have them, and their component looks the most similar to what we are trying to achieve. Lets not forget that no aria is better than "bad" aria.
I think so, we want the screen reader to read out that it is a menu, and how many menuitems it has

2023-11-15 12:31 UTC, Barsnes commented on packages/react/src/components/Dropdown/DropdownDivider/DropdownDivider.tsx
> +export const DropdownDivider = ({ ...rest }: DropdownDividerProps) => {
Will follow the same pattern as in `Modal`.

2023-11-15 12:33 UTC, Barsnes commented on packages/react/src/components/Dropdown/DropdownItem/DropdownItem.tsx
> +        role='menuitem'
No, not according to MDN: [ role='menuitem'](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/menuitem_role#examples)

2023-11-15 12:34 UTC, Barsnes commented on packages/react/src/components/Dropdown/DropdownGroup/DropdownGroup.tsx
> +          <Paragraph
`Heading` comes with a lot of unwanted styles. It's easier to use `Paragraph`, and cast it to a`H*`

2023-11-16 10:33 UTC, mimarz requested changes
Looks pretty dandy! 👍 

I think we should also have focus on first element when navigation is done by keyboard and open using the "Space" or "Enter" key, as per [aria best practice](https://www.w3.org/WAI/ARIA/apg/patterns/menu-button/).

What do you guys think? @mrosvik @Febakke @Thuneer

2023-11-16 10:33 UTC, mimarz commented on packages/react/src/components/DropdownMenu/DropdownMenu.mdx
> +- https://www.w3.org/WAI/tutorials/menus/flyout/#flyoutnavkbbtn
-
```suggestion
- https://www.w3.org/WAI/tutorials/menus/flyout/#flyoutnavkbbtn
- https://www.w3.org/WAI/ARIA/apg/patterns/menu-button/
```

2023-11-16 11:47 UTC, Barsnes commented
> Looks pretty dandy! 👍
> 
> I think we should also have focus on first element when navigation is done by keyboard and open using the "Space" or "Enter" key, as per [aria best practice](https://www.w3.org/WAI/ARIA/apg/patterns/menu-button/).
> 
> What do you guys think? @mrosvik @Febakke @Thuneer

I think it should focus the first element. What about focus trap?

2023-11-16 12:40 UTC, mimarz approved these changes
Maybe add an `ArsgTable` for `DropdownMenu.Group` in `DropdownMenu.mdx`, apart from that great work!

![great-job](https://github.com/digdir/designsystem/assets/1070981/4bc894eb-b7d9-4780-ae88-595bdf4fdc7d)

2023-11-16 13:27 UTC, Thuneer approved these changes

2023-11-16 13:28 UTC, Thuneer commented
Great job!

2023-11-16 14:04 UTC, merged