feat(sizing): Syncronize sizing between Figma and React components
digdir/designsystem pull request #1084
Opened 2023-11-13 10:42 UTC by Barsnes

Resolves #1075

2023-11-16 09:03 UTC, mimarz commented
Make sure to test for this use-case #1042

2023-11-16 14:31 UTC, Barsnes commented
Waiting on @mrosvik's changes to `HelpText` for this to be moved to review. #1107

2023-11-17 07:06 UTC, mrosvik commented
@Barsnes 

`Small`, `medium` and `large` sizes is now added to both `HelpText` and `Popover` in Figma ✅

https://www.figma.com/file/vpM9dqqQPHqU6ogfKp5tlr/Felles-komponenter?type=design&node-id=20759%3A80130&mode=design&t=pFMkxezHjX6MVQWE-1

2023-11-17 07:06 UTC, mrosvik commented
@Barsnes 

`Small`, `medium` and `large` sizes is now added to both `HelpText` and `Popover` in Figma ✅

https://www.figma.com/file/vpM9dqqQPHqU6ogfKp5tlr/Felles-komponenter?type=design&node-id=20759%3A80130&mode=design&t=pFMkxezHjX6MVQWE-1

2023-11-21 09:01 UTC, mimarz requested changes
Not sure if this was intentional or not but looks like you missed to update the `padlock` unit size from `rem` to `em` on several other "form" components, `Textfield`, `Textarea` and `NativeSelect`

You have not done anything with the heights of `NativeSelect` or `Textfield` so the bug #1042 is not fixed which I was under the impression we wanted to fix by doing this PR also

2023-11-21 11:04 UTC, Barsnes commented on packages/react/src/components/Pagination/Pagination.module.css
> +.listitem.large {
Were we not supposed to remove `compact`?

2023-11-22 09:23 UTC, Thuneer commented on packages/react/src/components/Pagination/Pagination.module.css
> +.listitem.large {
Yes, the compact prop is needed for the pagination component to fit horizontally on the smallest mobile devices. From testing it has to be smaller than 352px in width.

2023-11-22 11:47 UTC, mimarz commented on packages/react/src/components/Pagination/Pagination.module.css
> +.listitem.large {
Added the compact class back.

2023-11-22 12:59 UTC, mimarz approved these changes
LGTM 👍 

We still have two bugs related to sizing, #1042 and #1146 which we will solve in separate PRs

2023-11-22 19:10 UTC, merged