feat(SkipLink): New component
digdir/designsystem pull request #1111
Opened 2023-11-17 07:24 UTC by stianmorsund

Resolves #1055

2023-11-17 07:53 UTC, Barsnes requested changes
Looks good ✨ 
Commented on some minor things that needs tweaking

2023-11-17 07:53 UTC, Barsnes commented on packages/react/src/components/SkipLink/SkipLink.tsx
> +  className?: string;
You don't need to put classname here, you get it from `...rest`.

2023-11-17 07:53 UTC, Barsnes commented on packages/react/src/components/SkipLink/SkipLink.tsx
> +  href?: string;
This should be required

2023-11-17 07:53 UTC, Barsnes commented on packages/react/src/components/SkipLink/SkipLink.stories.tsx
> +export const Preview: Story = () => (
You have a type error here:
```
src/components/SkipLink/SkipLink.stories.tsx(12,14): error TS2559: Type '() => Element' has no properties in common with type 'StoryAnnotations<ReactRenderer, { children: ReactNode; className?: string | undefined; href?: string | undefined; } & AnchorHTMLAttributes<HTMLAnchorElement>>'.
```

2023-11-17 07:53 UTC, Barsnes commented on packages/react/src/components/SkipLink/SkipLink.module.css
> +  padding: 15px;
Padding is different in figma, you should be using spacing tokens

2023-11-21 10:45 UTC, mimarz approved these changes
Awesomesauce! This looks good to me 😊 Thank you for contributing to development of our components, much appreciated! 👏 

![awesome-sauce-david-tennant](https://github.com/digdir/designsystem/assets/1070981/f7a0d854-878c-4538-9314-7a20b066f0f5)

2023-11-22 07:01 UTC, merged