build: :triangular_flag_on_post: Disable tree-shaking
digdir/designsystem pull request #1163
Opened 2023-11-28 12:45 UTC by mimarz

2023-11-28 13:29 UTC, Magnusrm commented
> I have published a new potential under the `next` tag, could you please test again @Magnusrm ? 🙏

Nice! I'll test it 🤞 😁

2023-11-28 14:00 UTC, Magnusrm commented
Tested in `app-frontend-react`. The checkbox labels are fixed and no other designsystem components broke 🎉

2023-11-29 07:45 UTC, Barsnes requested changes
Could we just comment out the removed code, since we will be adding this back as soon as possible?

2023-11-29 07:52 UTC, mimarz commented
> Could we just comment out the removed code, since we will be adding this back as soon as possible?

Not all code will be relevant/needed, but I can comment out the bits we'll need for future tree-shaking :)

2023-11-29 09:23 UTC, Barsnes approved these changes
🚀

2023-11-29 09:26 UTC, merged