feat(Spinner): Add spinner component
digdir/designsystem pull request #162
Opened 2023-02-20 12:22 UTC by framitdavid

Created the new spinner component based on Figma sketch. https://www.figma.com/file/vpM9dqqQPHqU6ogfKp5tlr/Felles---Core-Components?node-id=9104%3A49626&t=E0vLjMXEaaBIgtzU-0

2023-02-21 13:06 UTC, mimarz requested changes
Pretty Spinner! Works as advertised 👍 

Added some suggestions for docs, improving DX and allowing more control and expected behaviour from react component.

I see we have some improvements to do in Storybook to make ease of documenting components. I'll some issues regarding this.

Suggest also using [Github keywords ](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) for linking it to the issue. Suggest using the resolve keyword.

2023-02-21 14:10 UTC, framitdavid commented on packages/react/src/components/Spinner/Spinner.stories.mdx
> +  }}
I agree, was just copying the other stories to make it consistent within the codebase. I think we should consider changing the way we are writing stories. :)

2023-02-21 14:12 UTC, framitdavid commented on packages/react/src/components/Spinner/Spinner.tsx
> +  const sizeMap: Record<Size, number> = {
I agree that those static values can be outside the render function. I prefer to have the Record type to ensure the key is consistent with the type. Record<**Size**, number>, this ensures that the map-object contains only keys that are defined within the type.

2023-02-21 14:12 UTC, framitdavid commented on packages/react/src/components/Spinner/Spinner.tsx
> +  const variantMap: Record<
Yeap! :)

2023-02-21 14:15 UTC, framitdavid commented on packages/react/src/components/Spinner/Spinner.tsx
> +      data-testid='spinner-container'
Generally, we should avoid using data-testid totally. Using test-id should be a warning of potentially bad accessibility support. We should be able to query almost everything by using getByRole etc. Anyway, for this component, I removed the <div/> and the consumer of this component needs to ensure they stay accessible based on the use case of the spinner.

2023-02-21 14:16 UTC, framitdavid commented on packages/react/src/components/Spinner/Spinner.tsx
> +    <div
Removed, ref. previous comment. :)

2023-02-21 14:17 UTC, framitdavid commented on packages/react/src/components/Spinner/Spinner.test.tsx
> +
I prefer to not test CSS within our unit tests. Based on the conversation we had I do not write more tests for this component. :)

2023-02-21 14:24 UTC, framitdavid commented on packages/react/src/components/Spinner/Spinner.tsx
> +};
Thanks for the great feedback!

Regarding _"Maybe more of a preference but if you write the string literal directly in SpinnerProps it gets listed out in the IDE intellisense. You decide"_. The reason why I have created types is to reuse the type within the Record to ensure the map object keys stay consistent with the props. :)

2023-02-22 06:40 UTC, mimarz approved these changes
LGTM 👍

2023-02-22 06:43 UTC, mimarz requested changes
Seems you are missing and `index.ts` with export of the component and subsequently export in `src/index.ts`. Was this intended?

2023-02-22 09:02 UTC, mimarz approved these changes
![thumbs-up-borat](https://user-images.githubusercontent.com/1070981/220572247-51599db3-1993-4261-9cd2-472d68be1007.gif)

2023-02-22 09:05 UTC, merged