fix(CheckboxRadioTemplate): Fix perceived WAVE accessibility error
digdir/designsystem pull request #218
Opened 2023-03-09 09:32 UTC by Magnusrm

Replaces accessibility solution for labels for screen-readers with using `visually hidden` css to make WAVE happy when the labels are hidden for a checkbox / radiobutton.

NB!
It is important to note that even though WAVE complains of missing labels for the inputs when the labels are set to hidden, screen readers that have been tested (mac VoiceOver) works as intended and reads the correct labels set with `aria-labeledby`. Other accessibility tools like axe DevTools and Siteimprove have been tested and give no warning.

2023-03-09 18:14 UTC, mimarz requested changes
Would it work to conditionally render the the "labelAndDescription" span instead of applying a css class to hide it? 

The `label` is applied as `aria-label` on `input` when `showLabel` is false.

2023-03-09 18:14 UTC, mimarz commented on packages/react/src/components/RadioButton/RadioButton.test.tsx
> +    ).toContain('visuallyHidden');
Same as previous comment about `parentElement`

2023-03-13 12:18 UTC, mimarz commented
I've made a few changes to linting, formating and other configs, so I recommend you rebase your branch with the latest changes before you continue! 😄

2023-03-13 14:16 UTC, Magnusrm commented
> I've made a few changes to linting, formating and other configs, so I recommend you rebase your branch with the latest changes before you continue! 😄

Thanks for the heads up! I am focusing on a task in the altinn apps team at the moment, so i have put this on hold for now 😁

2023-04-24 12:07 UTC, closed without merging

2023-04-24 12:07 UTC, mimarz commented
Closed by request of @Magnusrm