chore: Remove any usage from storefront
digdir/designsystem pull request #234
Opened 2023-03-14 06:53 UTC by Thuneer

2023-03-14 10:40 UTC, mimarz requested changes
Excellent work on removing the anys and getting some proper type safety in there! <3

2023-03-14 10:40 UTC, mimarz commented on .hintrc
This looks to be a configuration file for linter and hiner [Webhint](https://webhint.io/)? Was there a specific reason for using this? 

We are using [ESLint](https://eslint.org/) for this purpose and we should not need to use two different tools for solving the same problem.

2023-03-14 10:59 UTC, Thuneer commented on .hintrc
I think I misclicked when I was using the "Quick fix" feature in VSCode. I removed the file in the next commit.

2023-03-15 08:13 UTC, mimarz commented on .hintrc
huh, weird. Never heard of it before. Looks like its maybe something Microsoft is trying to push now 🙈

2023-03-15 08:16 UTC, mimarz approved these changes
How does it feel? Good amount of cleaning up done now! 🧹 👍

2023-03-15 08:55 UTC, merged