Feat/351 countdown remaining letters
digdir/designsystem pull request #365
Opened 2023-05-08 12:34 UTC by framitdavid

**Implemented feature:**
As a user, I want to see how many characters I can type in an input field and have a countdown of the remaining characters as I type. If I exceed the character limit, the text should appear in red, and the number of excess characters should be displayed.

**Considerations:**
The text that appears, such as "4 characters left" or "2 characters too long," cannot be hard-coded in just Norwegian or English since this component may be used in other languages - how to solve this?

**Solutions:**
I implemented a new object named CharLimitInformation which takes a few parameters such as: 
```typescript
hasExceededCharLimit: boolean;
screenReaderMaxCharDescription: string;
remainingCharLimitMessage: string;
```

I implemented the feature in this way to make it as user-friendly as possible for the component's consumers. We don't determine whether the state is invalid or how the user-facing text or messages should be formulated or translated. Instead, we indicate the input's invalidity based on information provided by the component's consumer. This means that the consumer has complete control over the messages and when to mark the input as invalid. We also ensure accessibility and confirm that it functions as expected.

Since we don't handle translations, we can't accurately determine where to place the counter number within the countdown message. If we had included a maxCount property and implemented our own countdown logic, it would only serve the purpose of marking the input field as invalid. However, our consumers would still need to implement their own counter function to provide correct texts and translations to our component. Therefore, I believe that the API is clearer and easier to use as implemented in this pull request, meaning we take all the needed information from the consumer not only the messages.

2023-05-08 12:52 UTC, TomasEng commented
Great job! As a consumer, I would expect the counter to work automatically though. Have you considered making the prop a function, like this?
`remainingCharLimitMessage: (count: number) => count + ' tegn igjen'`

2023-05-10 07:00 UTC, mimarz commented
Me and @framitdavid did a review together in a huddle on Slack as Github had problems yesterday so i was unable to write a review here. 

We agreed to update the stories to new format, changes to how documentation was declared, internal count logic and revised component api for character limit.

2023-05-11 10:21 UTC, TomasEng approved these changes
Storartet! Du må nok endre tittelen på PR-en, så den blir med i endringsloggen: https://github.com/digdir/designsystem#commit-%EF%B8%8F

2023-05-11 10:21 UTC, TomasEng commented on packages/react/src/components/TextArea/TextArea.stories.tsx
> +      srLabel: 'Tekstområde har plass til 10 tegn.',
🤓 
```suggestion
      srLabel: 'Tekstområdet har plass til 10 tegn.',
```

2023-05-12 06:37 UTC, mimarz requested changes
Some minor suggestions :)

When testing on MacOS I was not getting the `srLabel` read out. This was also the case when testing the same from other design systems so it might just be a Voiceover thing. Would be benifical to test with NVDA/JAWS.

Reading out the label when the limit was exceeded worked good with Voiceover :) 

As for the prop name, maybe just call it `characterLimit` instead of `charLimit`? This might just be a personal preference, think it felt better with `characterLimit` 😅 What do you guys think @TomasEng @framitdavid ?

2023-05-12 06:37 UTC, mimarz commented on packages/react/src/components/TextField/TextField.tsx
> +} & HTMLAttributes<HTMLInputElement>;
Suggest we keep the existing "extend" as long as we are using the `react-number-format` library as `HTMLAttributes<*>` (and `InputHTMLAttributes<*>` throws error with `react-number-format`) does not include the correct `input` attributes. 

They are however included in the `NumericFormatProps | PatternFormatProps`. 

We can have a look at cleaning this up later :) 

You can still use `type` just replace `HTMLAttributes<HTMLInputElement>` with ```Omit<NumericFormatProps | PatternFormatProps,'readOnly' | 'value' | 'defaultValue'>```

2023-05-12 06:57 UTC, framitdavid commented
> Some minor suggestions :)
> 
> When testing on MacOS I was not getting the `srLabel` read out. This was also the case when testing the same from other design systems so it might just be a Voiceover thing. Would be benifical to test with NVDA/JAWS.
> 
> Reading out the label when the limit was exceeded worked good with Voiceover :)
> 
> As for the prop name, maybe just call it `characterLimit` instead of `charLimit`? This might just be a personal preference, think it felt better with `characterLimit` 😅 What do you guys think @TomasEng @framitdavid ?

Great review @mimarz! I agree to rename the charLimit to characterLimit. 😎

2023-05-12 08:07 UTC, TomasEng commented
> Great review @mimarz! I agree to rename the charLimit to characterLimit. 😎

I agree as well! Not a fan of abbreviations.

2023-05-12 08:15 UTC, TomasEng commented
> When testing on MacOS I was not getting the `srLabel` read out. This was also the case when testing the same from other design systems so it might just be a Voiceover thing. Would be benifical to test with NVDA/JAWS.

Tested with NVDA, it works 🙂

2023-05-12 08:19 UTC, TomasEng approved these changes

2023-05-12 10:29 UTC, mimarz requested changes
As mentioned in DM, the inline prop docs uses jsdoc, so it needs to start with `/**` for it to work.

You will also have to copy the `characterLimit` docs on each property in `Textarea` & `Textfield` as its not pulled from `Inputwrapper`.

Suggets shortening down the `characterLimit` docs and use code ticks "``" for when referencing other props in the documentation text so its clear for users that you are referencing props.

2023-05-15 07:53 UTC, mimarz commented
jsdoc and props seems to work good now! 👏 
![image](https://github.com/digdir/designsystem/assets/1070981/cd58d69d-ff1c-4379-80eb-f60478d50e73)

2023-05-15 07:54 UTC, mimarz approved these changes
LGTM! 👍 

Thanks for contributing new features and doing some cleaning up! 🧹❤️

2023-05-15 11:47 UTC, merged