feat(ToggleGroup): Create new ToggleGroup component
digdir/designsystem pull request #813
Opened 2023-09-13 11:31 UTC by Magnusrm

2023-09-27 17:55 UTC, mrosvik commented
Great work! 👏🏻 🤩
 
 I think..
- `Focus`-state should behave like the `radio` component (only show with tab-focus).
- We should add an example with only icons and make sure the buttons are square.

<img width="483" alt="image" src="https://github.com/digdir/designsystem/assets/1464915/8637ad2e-f120-43ac-93b4-f9b02822d915">

2023-09-28 05:10 UTC, Magnusrm commented
> * `Focus`-state should behave like the `radio` component (only show with tab-focus).
> * We should add an example with only icons and make sure the buttons are square.

@mrosvik 
I agree on adding example with only icons, nice catch! 😊 I'll also update the focus behaviour 👍

2023-09-28 06:57 UTC, mimarz requested changes
Oh boy! Nice work on the Roving utility component 👌 

Looks very good, mostly just feedback on some docs and clean code. 

![ohboy-golden-girls](https://github.com/digdir/designsystem/assets/1070981/370a6391-aa4d-4ff6-b2fa-5e6b4308de38)

2023-09-28 06:57 UTC, mimarz commented on packages/react/src/components/ToggleGroup/ToggleGroup.tsx
> +  /** Value of the ToggleGroup component. Set when you want to controll the value of the component. */
```suggestion
  /** Controlled state for `ToggleGroup` component. */
```

2023-09-28 06:57 UTC, mimarz commented on packages/react/src/components/ToggleGroup/ToggleGroup.tsx
> +  /** Default value of the ToggleGroup component. Set when you want to use the component as an uncontrolled component. */
```suggestion
  /** Default value. */
```

2023-09-28 06:57 UTC, mimarz commented on packages/react/src/components/ToggleGroup/ToggleGroup.tsx
> +  /** Function that is called when the value of the ToggleGroup component changes. The current value is available in the callback. */
```suggestion
  /** Callback with selected `ToggleGroupItem` `value` */
```

2023-09-28 06:57 UTC, mimarz commented on packages/react/src/components/ToggleGroup/ToggleGroup.tsx
> +  /** Size of the ToggleGroup component. */
```suggestion
  /** Changes items size and paddings */
```

2023-09-28 06:57 UTC, mimarz commented on packages/react/src/components/ToggleGroup/ToggleGroup.tsx
> +  /** Name of the ToggleGroup component. */
```suggestion
  /** Form element name */
```

2023-09-28 06:57 UTC, mimarz commented on packages/react/src/components/ToggleGroup/ToggleGroup.tsx
> +    const nameId = useId();
nitpicking, but suggest moving this to line 37 for better readability of code

2023-09-28 06:57 UTC, mimarz commented on packages/react/src/components/ToggleGroup/ToggleGroup.tsx
> +            name: name ?? `radiogroup-name-${nameId}`,
We should use the name of the component as thats where to data comes from when form is submitted.
```suggestion
            name: name ?? `togglegroup-name-${nameId}`,
```

2023-09-28 06:57 UTC, mimarz commented on packages/react/src/components/ToggleGroup/ToggleGroupItem/useToggleGroupitem.ts
> +  const buttonId = `toggleButton-${useId()}`;
```suggestion
  const buttonId = `togglegroup-item-${useId()}`;
```

2023-09-28 06:57 UTC, mimarz commented on packages/react/src/components/ToggleGroup/ToggleGroup.stories.tsx
> +  defaultValue: 'test',
Suggest removing this default value as it does not match the example used in preview.
```suggestion
  defaultValue: 'test',
```

2023-09-28 06:57 UTC, mimarz commented on packages/react/src/components/ToggleGroup/ToggleGroup.stories.tsx
> +          Focus last item!
Suggest using the actual name/value for item for better readability.

```suggestion
          Focus Walnut
```

2023-09-28 06:57 UTC, mimarz commented on packages/react/src/components/ToggleGroup/ToggleGroup.stories.tsx
> +          Activate middle button!
```suggestion
          Select Peanut
```

2023-09-28 06:57 UTC, mimarz commented on packages/react/src/components/ToggleGroup/ToggleGroup.tsx
> +
Suggest adding a small jsdoc for the actual component. Look at `Textfield` for example

2023-09-28 07:02 UTC, mimarz commented
Suggest also updating the [Overview.mdx](https://github.com/digdir/designsystem/blob/cf8343a872d4f19ca136f868a7e1bbebf01bee18/packages/Overview.mdx#L45C6-L45C6) to point to this new "felles" component :)

2023-09-28 10:24 UTC, mimarz approved these changes
Some more suggestions on docs else looking good! 👍

2023-09-28 10:24 UTC, mimarz commented on packages/react/src/components/ToggleGroup/ToggleGroup.stories.tsx
> +      defaultValue='Peanut'
For our Preview's always only use `args` for defining prop values so its clear to our users in the props table that this is defined without needing to inspect code.

2023-09-28 10:24 UTC, mimarz commented on packages/react/src/components/ToggleGroup/ToggleGroup.stories.tsx
> +};
No need for a separate story for uncontrolled as `Preview` already shows this. 
```suggestion
```

2023-09-28 10:24 UTC, mimarz commented on packages/react/src/components/ToggleGroup/ToggleGroup.mdx
> +<Canvas of={ToggleGroupStories.Uncontrolled} />
No need for a separate story for uncontrolled as Preview already shows this.
```suggestion
```

2023-09-28 11:12 UTC, merged