Chore: upgrade rollup and plugins
digdir/designsystem pull request #882
Opened 2023-10-02 11:24 UTC by Barsnes

Resolves #861

2023-10-03 07:15 UTC, Barsnes commented
We are now compiling with `tsc`, and then running rollup to add tree shaking. 
This is the final output when using the library in `create-react-app` and importing **only** `Button` and `Accordion`
![image](https://github.com/digdir/designsystem/assets/14057205/a1e238de-c24c-4fc7-9b12-8de996cbfae2)

2023-10-03 10:04 UTC, mimarz requested changes
Nice work! 

Made some comments on stuff and suggest trying to also remove the dts plugin as I don't think its needed anymore?

Looking at what rollup does at this point, maybe we won't need it anymore in future as its not doing much now.

I think we can also remove `@rollup/plugin-json` and `@rollup/plugin-image`, but suggest a separate issue on that as to not interfer now.

2023-10-03 10:05 UTC, Barsnes commented on packages/react/rollup.config.js
>  import dts from 'rollup-plugin-dts';
I think we can do that yes, good catch.
testing..

2023-10-03 17:39 UTC, mimarz approved these changes
Awesome work! 👏 Feels like a big load was shaken off! <3 

I would like to test using something like `bun` or `esbuild` to speed up build time, but we can save to for another time once the rest of our planned changes are done :)

2023-10-04 06:13 UTC, merged

2023-10-04 06:21 UTC, mimarz commented
resolved #169