Docs/guidelines checkbox
digdir/designsystem pull request #904
Opened 2023-10-05 21:06 UTC by mrosvik

2023-11-13 07:55 UTC, mrosvik commented
@Ildest should have a look before this is merged.

2023-11-13 13:52 UTC, mimarz requested changes

2023-11-13 13:52 UTC, mimarz commented on packages/react/src/components/form/Checkbox/Checkbox.mdx
> +Det skal være mulig å velge en `checkbox` uten å klikke, bare ved å trykke på Tab.
Denne linjen er ikke helt korrekt. Trykk Tab vil sette neste "fokuserbar" element i fokus. Var det meningen at det skulle stå "space" (som er vanlig måte å velge en checkbox)?

2023-11-13 13:52 UTC, mimarz commented on packages/react/src/components/form/Checkbox/Checkbox.mdx
> +- Ikke bruk `checkbox` når det er flere enn 7 alternativer.
```suggestion
- Ikke bruk `Checkbox` når det er flere enn 7 alternativer.
```

2023-11-13 13:52 UTC, mimarz commented on packages/react/src/components/form/Checkbox/Checkbox.mdx
> +Ikke bruk `readonly` med mindre det er absolutt umulig å gjøre noe annet.
```suggestion
Ikke bruk `readOnly` med mindre det er absolutt umulig å gjøre noe annet.
```

2023-11-13 13:52 UTC, mimarz commented on packages/react/src/components/form/Checkbox/Checkbox.mdx
> +- Hvis det er flere enn 7 svaralternativer bruk heller [`NativeSelect`](/docs/altinn-nativeselect--docs) eller `Combobox` (kommer snart).
```suggestion
- Hvis det er flere enn 7 svaralternativer bruk heller [`NativeSelect`](/docs/felles-nativeselect--docs) eller `Combobox` (kommer snart).
```

2023-11-13 13:52 UTC, mimarz commented on packages/react/src/components/form/Checkbox/Checkbox.mdx
> +- Ikke bruk `checkbox` til å skjule eller vise innhold, eller til gjensidig utelukkende alternativer.
```suggestion
- Ikke bruk `Checkbox` til å skjule eller vise innhold, eller til gjensidig utelukkende alternativer.
```

2023-11-13 13:52 UTC, mimarz commented on packages/react/src/components/form/Checkbox/Checkbox.mdx
> +Det skal være mulig å velge en `checkbox` uten å klikke, bare ved å trykke på Tab.
```suggestion
Det skal være mulig å velge en `Checkbox` uten å klikke, bare ved å trykke på Tab.
```

2023-11-13 13:57 UTC, Barsnes commented on packages/react/src/components/form/Checkbox/Checkbox.mdx
> +Ikke bruk `readonly` med mindre det er absolutt umulig å gjøre noe annet.
Burde tittelen bli endra her også? `Readonly` er vel teknisk sett ikkje eit ord, ser [her](https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/r/read-only) at microsoft seier du skal bruke `-`:

2023-11-14 06:28 UTC, mrosvik commented on packages/react/src/components/form/Checkbox/Checkbox.mdx
> +Det skal være mulig å velge en `checkbox` uten å klikke, bare ved å trykke på Tab.
Bra observert 👏🏻

2023-11-14 06:34 UTC, mrosvik commented on packages/react/src/components/form/Checkbox/Checkbox.mdx
> +Det skal være mulig å velge en `checkbox` uten å klikke, bare ved å trykke på Tab.
Nytt forslag: 

Det skal være mulig å flytte fokus til `Checkbox`, ved å trykke `Tab` på tastaturet. Det skal være mulig å merke og fjerne avmerking ved å trykke `Space`. 

@Ildest

2023-11-15 09:31 UTC, mimarz approved these changes
LGTM 👍

2023-11-15 09:31 UTC, merged