fix(NativeSelect): Refactor away from `InputWrapper`
digdir/designsystem pull request #955
Opened 2023-10-17 12:01 UTC by Barsnes

Resolves #919

2023-10-17 12:57 UTC, Barsnes commented
I believe I have implemented your wishes @mimarz. Let me know if anything is missing/wrong

2023-10-19 06:57 UTC, mimarz requested changes

2023-10-19 06:57 UTC, mimarz commented on packages/react/src/components/form/NativeSelect/NativeSelect.module.css
> +.input {
Suggest renaming this class to `select`

2023-10-19 06:57 UTC, mimarz commented on packages/react/src/components/form/NativeSelect/NativeSelect.module.css
> +  padding: 0 var(--fds-spacing-3);
Looked like to much padding with `spacing-3`, suggest `spacing-2`
```suggestion
  padding: 0 var(--fds-spacing-2);
```

2023-10-19 06:57 UTC, mimarz commented on packages/react/src/components/form/NativeSelect/NativeSelect.tsx
> +   * @default 'medium'
Remove the ticks as its showing wrong value in props table.
![image](https://github.com/digdir/designsystem/assets/1070981/15831a44-8b42-4c0f-80fa-14c95b56c5dd)

```suggestion
   * @default medium
```

2023-10-19 06:57 UTC, mimarz commented on packages/react/src/components/form/NativeSelect/NativeSelect.tsx
> +  disabled?: boolean;
Suggest removing this to be consistent with other components, as we haven't documented other untouched native props

2023-10-19 06:57 UTC, mimarz commented on packages/react/src/components/form/NativeSelect/NativeSelect.tsx
> +            weight='medium'
missing `size={size}` prop

2023-10-19 07:54 UTC, mimarz approved these changes
![power-power-rangers](https://github.com/digdir/designsystem/assets/1070981/fefe93fb-7f1c-4916-adce-a524aefec5fd)

2023-10-19 07:57 UTC, merged